<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<?php
$storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Store\Model\StoreManagerInterface');
$urlMedia = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="block newsletter block-subscribe popup" style="display:none;">
	<div id="popup-newsletter">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-popup-validate-detail">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter_popup')->toHtml();?>
        </form>
    </div>
</div>
<script type="text/javascript">
	require(['jquery', 'mage/cookies', 'Magento_Ui/js/modal/modal', 'Magento_Customer/js/customer-data'], 
		function($, cookie, modal, customerData){
			if(!parseInt(Themecfg.newsletter.enabled)) return;
	        
	        (function(selector){
	            var popupCookie = $.cookie('popupNewsletterOff');
	            var overlay = Themecfg.newsletter.overlayColor;
	            if(!popupCookie || popupCookie == 'undefined'){
	                var $content = $(selector);
	                var color   = Themecfg.newsletter.background_color;
	                var timeDelay = parseInt(Themecfg.newsletter.timeDelay);
	                var autoClose = Themecfg.newsletter.autoClose;
	                var timeClose = timeDelay + parseInt(Themecfg.newsletter.timeClose);
	                var imageUrl = "<?php echo $urlMedia; ?>" + 'magiccart/newsletter/' + Themecfg.newsletter.background_image;
	                var popup   = $('#popup-newsletter', $content);
	                var pwidth  = Themecfg.newsletter.width;
	                var pheight = Themecfg.newsletter.height;
	                pwidth   = typeof pwidth  !== 'undefined' ? pwidth : 800;
	                pheight  = typeof pheight !== 'undefined' ? pheight : 400;
	                overlay  = typeof overlay !== 'undefined' ? overlay : '#363636';
	                if(Themecfg.newsletter.background_image) popup.css('background-image', 'url(' + imageUrl + ')');
	                else if(color) popup.css('background-color', color);
	                var popupOff = false;
					$(window).on('resize scroll', function() {
						/* Optimize speed */
						if(popupOff) return;
		                setTimeout( function() {
	                        modal({
	                            type: 'popup',
	                            modalClass: 'popup-newsletter',
	                            responsive: true, 
	                            buttons: false                       	
	                        }, popup);
		                    popup.modal('openModal');
		                    $(".modal-popup .modal-inner-wrap").css({ "width":pwidth, "height":pheight }); 
		                }, timeDelay);
		                popupOff = true;
					});
	                if(Themecfg.newsletter.autoClose > 0) setTimeout(function(){$.fancybox.close()}, timeClose);
	                $('.subscribe-bottom input', popup).on('click', function(){
	                    if($(this).parent().find('input:checked').length){
	                        $.cookie('popupNewsletterOff', true);
	                    } else {
	                        $.cookie('popupNewsletterOff', undefined);
	                    }
	                });
	                if(Themecfg.newsletter.firstOnly > 0) $.cookie('popupNewsletterOff', true);
	                popup.find('.actions button').on('click', function(){
	                    $.cookie('popupNewsletterOff', true);
	                    $.cookie('popupNewsletterMessages', true, {domain: document.domain});
	                });
					
					$(document).on('click', '.popup-newsletter .action-close', function() {
	                	$('.popup-newsletter').removeClass('_show').siblings('.modals-overlay').hide();
	                	$('body').removeClass('_has-modal');
					});
	            } else {
					if($.cookie('popupNewsletterMessages')){
						var messages = $.cookieStorage.get('mage-messages');
						if(messages.length){
							var $messages = $('.messages').attr('id', 'popupNewsletterMessages').wrap( "<div></div>" );
							setTimeout(function () {
								modal({
									type: 'popup',
									modalClass: 'popup-messages',
									responsive: true, 
									buttons: false                       	
								}, $messages);
								$messages.modal('openModal');
								
								$.cookie('popupNewsletterMessages', '', {domain: document.domain});
							}, 1000);
							setTimeout(function () {
								$messages.modal('closeModal');
							}, 5000);
						}
					}
	            }

	        })(".block-subscribe.popup");
	});
</script>
