<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-copyright">
		<div class="main1">
			<small class="copyright">
				<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
			</small>
		</div>
	<a href="#" id="backtotop"><span class="icon-top fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Top')?></span></a>
</div>
